"""followers

Revision ID: 29785381c469
Revises: 8dd5a0ba8d45
Create Date: 2018-09-28 08:45:05.624734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29785381c469'
down_revision = '8dd5a0ba8d45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
