"""Add about_me and last_seen to users

Revision ID: 342bc2728e27
Revises: be3b93b3e4b1
Create Date: 2018-09-27 21:12:05.836788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '342bc2728e27'
down_revision = 'be3b93b3e4b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'about_me')
    # ### end Alembic commands ###
