"""Unique Party Names

Revision ID: bd4f360c5c42
Revises: 29785381c469
Create Date: 2018-09-28 16:14:30.813581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd4f360c5c42'
down_revision = '29785381c469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'parties', ['title'])
    op.create_unique_constraint(None, 'songs', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'songs', type_='unique')
    op.drop_constraint(None, 'parties', type_='unique')
    # ### end Alembic commands ###
